// Code generated by Kitex v0.4.4. DO NOT EDIT.

package videoservice

import (
	"context"
	"douyin/shared/kitex_gen/video"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Feed(ctx context.Context, req *video.DouyinFeedRequest, callOptions ...callopt.Option) (r *video.DouyinFeedResponse, err error)
	Publish(ctx context.Context, req *video.DouyinPublishActionRequest, callOptions ...callopt.Option) (r *video.DouyinPublishActionResponse, err error)
	GetPublishedVideoList(ctx context.Context, req *video.DouyinGetPublishListRequest, callOptions ...callopt.Option) (r *video.DouyinGetPublishListResponse, err error)
	GetFavoriteVideoList(ctx context.Context, req *video.DouyinGetFavoriteListRequest, callOptions ...callopt.Option) (r *video.DouyinGetFavoriteListResponse, err error)
	GetPublishVideoIdList(ctx context.Context, req *video.DouyinGetPublishVideoIdListRequest, callOptions ...callopt.Option) (r *video.DouyinGetPublishVideoIdListResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kVideoServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kVideoServiceClient struct {
	*kClient
}

func (p *kVideoServiceClient) Feed(ctx context.Context, req *video.DouyinFeedRequest, callOptions ...callopt.Option) (r *video.DouyinFeedResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Feed(ctx, req)
}

func (p *kVideoServiceClient) Publish(ctx context.Context, req *video.DouyinPublishActionRequest, callOptions ...callopt.Option) (r *video.DouyinPublishActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Publish(ctx, req)
}

func (p *kVideoServiceClient) GetPublishedVideoList(ctx context.Context, req *video.DouyinGetPublishListRequest, callOptions ...callopt.Option) (r *video.DouyinGetPublishListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetPublishedVideoList(ctx, req)
}

func (p *kVideoServiceClient) GetFavoriteVideoList(ctx context.Context, req *video.DouyinGetFavoriteListRequest, callOptions ...callopt.Option) (r *video.DouyinGetFavoriteListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetFavoriteVideoList(ctx, req)
}

func (p *kVideoServiceClient) GetPublishVideoIdList(ctx context.Context, req *video.DouyinGetPublishVideoIdListRequest, callOptions ...callopt.Option) (r *video.DouyinGetPublishVideoIdListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetPublishVideoIdList(ctx, req)
}
