// Code generated by Kitex v0.4.4. DO NOT EDIT.

package messageservice

import (
	"context"
	"douyin/shared/kitex_gen/message"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return messageServiceServiceInfo
}

var messageServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "MessageService"
	handlerType := (*message.MessageService)(nil)
	methods := map[string]kitex.MethodInfo{
		"SendMessage":           kitex.NewMethodInfo(sendMessageHandler, newMessageServiceSendMessageArgs, newMessageServiceSendMessageResult, false),
		"GetMessageHistory":     kitex.NewMethodInfo(getMessageHistoryHandler, newMessageServiceGetMessageHistoryArgs, newMessageServiceGetMessageHistoryResult, false),
		"BatchGetLatestMessage": kitex.NewMethodInfo(batchGetLatestMessageHandler, newMessageServiceBatchGetLatestMessageArgs, newMessageServiceBatchGetLatestMessageResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "message",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.4.4",
		Extra:           extra,
	}
	return svcInfo
}

func sendMessageHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*message.MessageServiceSendMessageArgs)
	realResult := result.(*message.MessageServiceSendMessageResult)
	success, err := handler.(message.MessageService).SendMessage(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newMessageServiceSendMessageArgs() interface{} {
	return message.NewMessageServiceSendMessageArgs()
}

func newMessageServiceSendMessageResult() interface{} {
	return message.NewMessageServiceSendMessageResult()
}

func getMessageHistoryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*message.MessageServiceGetMessageHistoryArgs)
	realResult := result.(*message.MessageServiceGetMessageHistoryResult)
	success, err := handler.(message.MessageService).GetMessageHistory(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newMessageServiceGetMessageHistoryArgs() interface{} {
	return message.NewMessageServiceGetMessageHistoryArgs()
}

func newMessageServiceGetMessageHistoryResult() interface{} {
	return message.NewMessageServiceGetMessageHistoryResult()
}

func batchGetLatestMessageHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*message.MessageServiceBatchGetLatestMessageArgs)
	realResult := result.(*message.MessageServiceBatchGetLatestMessageResult)
	success, err := handler.(message.MessageService).BatchGetLatestMessage(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newMessageServiceBatchGetLatestMessageArgs() interface{} {
	return message.NewMessageServiceBatchGetLatestMessageArgs()
}

func newMessageServiceBatchGetLatestMessageResult() interface{} {
	return message.NewMessageServiceBatchGetLatestMessageResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) SendMessage(ctx context.Context, req *message.DouyinMessageActionRequest) (r *message.DouyinMessageActionResponse, err error) {
	var _args message.MessageServiceSendMessageArgs
	_args.Req = req
	var _result message.MessageServiceSendMessageResult
	if err = p.c.Call(ctx, "SendMessage", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetMessageHistory(ctx context.Context, req *message.DouyinGetMessageChatRequest) (r *message.DouyinGetMessageChatResponse, err error) {
	var _args message.MessageServiceGetMessageHistoryArgs
	_args.Req = req
	var _result message.MessageServiceGetMessageHistoryResult
	if err = p.c.Call(ctx, "GetMessageHistory", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) BatchGetLatestMessage(ctx context.Context, req *message.DouyinBatchGetLatestMessageRequest) (r *message.DouyinBatchGetLatestMessageResponse, err error) {
	var _args message.MessageServiceBatchGetLatestMessageArgs
	_args.Req = req
	var _result message.MessageServiceBatchGetLatestMessageResult
	if err = p.c.Call(ctx, "BatchGetLatestMessage", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
