// Code generated by Kitex v0.4.4. DO NOT EDIT.

package socialservice

import (
	"context"
	social "douyin/kitex_gen/social"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	RelationAction(ctx context.Context, Req *social.DouyinRelationActionRequest, callOptions ...callopt.Option) (r *social.DouyinRelationActionResponse, err error)
	RelationFollowList(ctx context.Context, Req *social.DouyinRelationFollowListRequest, callOptions ...callopt.Option) (r *social.DouyinRelationFollowListResponse, err error)
	RelationFollowerList(ctx context.Context, Req *social.DouyinRelationFollowerListRequest, callOptions ...callopt.Option) (r *social.DouyinRelationFollowerListResponse, err error)
	RelationFriendList(ctx context.Context, Req *social.DouyinRelationFriendListRequest, callOptions ...callopt.Option) (r *social.DouyinRelationFriendListResponse, err error)
	MessageAction(ctx context.Context, Req *social.DouyinMessageActionRequest, callOptions ...callopt.Option) (r *social.DouyinMessageActionResponse, err error)
	MessageChat(ctx context.Context, Req *social.DouyinMessageChatRequest, callOptions ...callopt.Option) (r *social.DouyinMessageChatResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kSocialServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kSocialServiceClient struct {
	*kClient
}

func (p *kSocialServiceClient) RelationAction(ctx context.Context, Req *social.DouyinRelationActionRequest, callOptions ...callopt.Option) (r *social.DouyinRelationActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RelationAction(ctx, Req)
}

func (p *kSocialServiceClient) RelationFollowList(ctx context.Context, Req *social.DouyinRelationFollowListRequest, callOptions ...callopt.Option) (r *social.DouyinRelationFollowListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RelationFollowList(ctx, Req)
}

func (p *kSocialServiceClient) RelationFollowerList(ctx context.Context, Req *social.DouyinRelationFollowerListRequest, callOptions ...callopt.Option) (r *social.DouyinRelationFollowerListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RelationFollowerList(ctx, Req)
}

func (p *kSocialServiceClient) RelationFriendList(ctx context.Context, Req *social.DouyinRelationFriendListRequest, callOptions ...callopt.Option) (r *social.DouyinRelationFriendListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RelationFriendList(ctx, Req)
}

func (p *kSocialServiceClient) MessageAction(ctx context.Context, Req *social.DouyinMessageActionRequest, callOptions ...callopt.Option) (r *social.DouyinMessageActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MessageAction(ctx, Req)
}

func (p *kSocialServiceClient) MessageChat(ctx context.Context, Req *social.DouyinMessageChatRequest, callOptions ...callopt.Option) (r *social.DouyinMessageChatResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MessageChat(ctx, Req)
}
