// Code generated by Fastpb v0.0.2. DO NOT EDIT.

package mod

import (
	fmt "fmt"
	fastpb "github.com/cloudwego/fastpb"
)

var (
	_ = fmt.Errorf
	_ = fastpb.Skip
)

func (x *Any) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_Any[number], err)
}

func (x *Any) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.TypeUrl, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *Any) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.Value, offset, err = fastpb.ReadBytes(buf, _type)
	return offset, err
}

func (x *Any) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	return offset
}

func (x *Any) fastWriteField1(buf []byte) (offset int) {
	if x.TypeUrl == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 1, x.TypeUrl)
	return offset
}

func (x *Any) fastWriteField2(buf []byte) (offset int) {
	if len(x.Value) == 0 {
		return offset
	}
	offset += fastpb.WriteBytes(buf[offset:], 2, x.Value)
	return offset
}

func (x *Any) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	return n
}

func (x *Any) sizeField1() (n int) {
	if x.TypeUrl == "" {
		return n
	}
	n += fastpb.SizeString(1, x.TypeUrl)
	return n
}

func (x *Any) sizeField2() (n int) {
	if len(x.Value) == 0 {
		return n
	}
	n += fastpb.SizeBytes(2, x.Value)
	return n
}

var fieldIDToName_Any = map[int32]string{
	1: "TypeUrl",
	2: "Value",
}
